[package]
name = "stereograma"
version = "0.1.0"
authors = ["Ted A. Gifford <tedfordgif@gmail.com>"]

[dependencies]
arr_macro = "*"
image = "^0.22"
libc = "^0.2.0"
ply-rs = "^0.1.1"
wavefront_obj = "5.1.0"

[lib]
crate-type = ["cdylib"]
